package:
  name: "pyearth"
  version: "0.1.16"

source:
  git_rev: 0.1.16
  git_url: https://github.com/changliao1025/pyearth.git

requirements:
  build:
    - python
    - setuptools
  
  run:
    - cartopy
    - matplotlib
    - netCDF4
    - numpy >=1.16
    - gdal
    - pandas
    - python >=3.8
    - scipy    
    - statsmodels
    
build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"    
    


about:
  home: https://github.com/changliao1025/pyearth
  license: MIT
  license_familY: MIT
  license_file: LICENSE
  summary: "Python for Earth Science"

extra:
  recipe-maintainers:
    - changliao1025