{% set name = "pyearth" %}
{% set version = "0.1.29" %}
{% set git_rev = "v" + version %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_rev: {{ git_rev }}
  git_url: https://github.com/changliao1025/pyearth

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python
    - setuptools
    - cython >=0.29.0
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - gdal
    - matplotlib-base
    - cartopy

test:
  imports:
    - pyearth
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/changliao1025/pyearth
  summary: Python for Earth Science.
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - changliao1025
