package:
  name: "pyearth"
  version: "0.1.2"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 10f4991d93dbd7a3a4d7f2fcc83faf5ae8203349655ddac0098c71acc59216db

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.6
  
  run:
    - julian
    - matplotlib
    - netCDF4
    - numpy    
    - osgeo
    - pandas
    - pyevtk
    - python
    - scipy    
    - statsmodels
    
    
    

about:
  home: https://github.com/changliao1025/pyearth
  license: MIT
  license_familY: MIT
  license_file: LICENSE
  summary: "Python for Earth"

extra:
  recipe-maintainers:
    - changliao1025