package:
  name: "pyearth"
  version: "0.1"

source:
  git_rev: v0.1
  git_url: https://github.com/changliao1025/pyearth

requirements:
  host:
    - python
    - setuptools
  build:
    - python
  run:
    - python
    - scipy
    - osgeo
    - numpy
    - matplotlib
    - statsmodels
    - pandas
    - adjustText

about:
  home: https://github.com/changliao1025/pyearth
  license: MIT
  license_familY: MIT
  license_file: LICENSE
  summary: "Python for Earth"

extra:
  recipe-maintainers:
    - changliao1025