package:
  name: "pyearth"
  version: "0.1.22"

source:
  git_rev: 0.1.22
  git_url: https://github.com/changliao1025/pyearth.git

requirements:
  build:
    - python
    - setuptools
  
  run:
    - python >=3.8
    - numpy
    - gdal    
    - matplotlib
    - cartopy
    - requests
    - netCDF4       
    - pandas    
    - scipy    
    - statsmodels
    
build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"    
    


about:
  home: https://github.com/changliao1025/pyearth
  license: BSD
  license_familY: BSD
  license_file: LICENSE.md
  summary: "Python for Earth Science"

extra:
  recipe-maintainers:
    - changliao1025